### PR TITLE
Added minLength to prevent empty properties

### PR DESCRIPTION
**Pull request by AnthorNet**

### CODE REVIEW

**Comment by jamesremuscat** [comment]
What would the difference in meaning be between submitting e.g. demandLevel as null and not submitting it? In general it's best to either mandate and allow null, or leave the property optional and prohibit null (as up to now) unless there's a difference in meaning between the two.

**Comment by AnthorNet** [comment]
With oneOf type array, we have to push multiple schema I think, 
one with both properties, one with only one of them and the reverse.

If I remove one of the property, it actually invalid the file.

**Comment by AnthorNet** [comment]
It's strange cause those properties aren't in "required"
I'll test a few more and come back, don't pull right now.

**Comment by AnthorNet** [comment]
Ok, tested, was testing wrong actually !
Reverted and ok to me.

**Pull request merged**
